LanguageInstallMVC/Controllers/TranslateController.cs
using LanguageInstall.Data.Data;
using LanguageInstall.Data.DTOs;
using LanguageInstall.Data.Model;
using LanguageInstall.Service.Service;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.AspNetCore.SignalR;
using LanguageInstall.Service.SignalR;

namespace LanguageInstallMVC.Controllers
{
    public class TranslateController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly ITranslationService _translationService;
        private readonly IHubContext<ProgressHub> _hubContext;

        public TranslateController(AppDbContext dbContext, ITranslationService translationService, IHubContext<ProgressHub> hubContext)
        {
            _dbContext = dbContext;
            _translationService = translationService;
            _hubContext = hubContext;
        }



        // Index View
        public async Task<IActionResult> Index()
        {
            var data = await _dbContext.MainTables
                .Include(mt => mt.Translations)
                .Select(mt => new MainTableDto
                {
                    ID = mt.ID,
                    EnglishText = mt.EnglishText,
                    Translations = mt.Translations.ToDictionary(t => t.LanguageCode, t => t.TranslatedText)
                })
                .ToListAsync();

            return View(data);
        }

        // Translate View
        public IActionResult Translate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Translate(string text, string targetLanguage)
        {
            if (string.IsNullOrWhiteSpace(text) || string.IsNullOrWhiteSpace(targetLanguage))
            {
                ViewBag.Error = "Text and target language are required.";
                return View();
            }

            try
            {
                var translatedText = await _translationService.PerformTranslation(text, targetLanguage);
                ViewBag.TranslatedText = translatedText;
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"An error occurred: {ex.Message}";
            }

            return View();
        }

        // Translate All Records


        public IActionResult TranslateAll()
        {
            
            //var result = _dbContext.LanguageLists
            //    .Where(lang => !_dbContext.Translation
            //    .Any(trans => trans.LanguageCode == lang.LanguageCode))
            //    .ToList();

            var distinctTranslationCodes = _dbContext.Translation
                .Select(trans => trans.LanguageCode)
                .Distinct();

            var result = _dbContext.LanguageLists .ToList();


            return View(result);
        }


        [HttpPost]
        public async Task<IActionResult> TranslateAll(string languageCode, string translationQuality)
        {
            int sleepTime;

            switch (translationQuality)
            {
                case "Good":
                    sleepTime = 2000; // 1 second
                    break;
                case "Better":
                    sleepTime = 3000; // 2 seconds
                    break;
                case "Best":
                    sleepTime = 4000; // 3 seconds
                    break;
                default:
                    sleepTime = 2000; // Default to 2 seconds if no quality is selected
                    break;
            }

            int o = 1;

            var englishTexts = await _dbContext.MainTables
                .Include(mt => mt.Translations)
                .Where(mt => !mt.Translations.Any(t => t.LanguageCode == languageCode)).ToListAsync();

            int total = englishTexts.Count;
            ViewBag.total = total;

            var options = new ChromeOptions();
            options.AddArgument("--headless");
            options.AddArgument("--disable-gpu");
            options.AddArgument("--no-sandbox");

            using (var driver = new ChromeDriver(options))
            {
                try
                {
                    string url = $"https://translate.google.com/?hl=en&sl=en&tl={languageCode}&op=translate";
                    driver.Navigate().GoToUrl(url);

                    Thread.Sleep(sleepTime);

                    var sourceTextBox = driver.FindElement(By.XPath("//textarea[@aria-label='Source text']"));

                    foreach (var item in englishTexts)
                    {
                        sourceTextBox.Clear();
                        sourceTextBox.SendKeys(item.EnglishText);
                        Thread.Sleep(sleepTime);

                        var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
                        var translationContainer = wait.Until(d => d.FindElement(By.ClassName("usGWQd")));
                        var result = translationContainer.Text;

                        var translation = new Translation
                        {
                            MainTableID = item.ID,
                            LanguageCode = languageCode,
                            TranslatedText = result,
                           
                        };

                        _dbContext.Translation.Add(translation);
                        await _dbContext.SaveChangesAsync();

                        // Send progress to the client
                        int progress = (o++ * 100) / total;
                        await _hubContext.Clients.All.SendAsync("UpdateProgress", progress, total);

                    }
                    // Notify clients when the operation is completed
                    await _hubContext.Clients.All.SendAsync("OperationCompleted");
                }
                catch (Exception ex)
                {
                    throw new Exception($"Error during translation: {ex.Message}");
                }
                finally
                {
                    driver.Quit();
                }
            }

            return RedirectToAction("Index", "Translations");
        }


        //best backupu
        //[HttpPost]
        //public async Task<IActionResult> TranslateAll(string languageCode)
        //{
        //    var sleepTime = 2000;
        //    int o = 1;

        //    var englishTexts = await _dbContext.MainTables
        //        .Include(mt => mt.Translations)
        //        .Where(mt => !mt.Translations.Any(t => t.LanguageCode == languageCode)).ToListAsync();

        //    ViewBag.total = englishTexts.Count;

        //    var options = new ChromeOptions();
        //    // options.AddArgument("--headless"); // Run browser in headless mode
        //    options.AddArgument("--disable-gpu");
        //    options.AddArgument("--no-sandbox");

        //    using (var driver = new ChromeDriver(options))
        //    {
        //        try
        //        {
        //            // Open Google Translate
        //            string url = $"https://translate.google.com/?hl=en&sl=en&tl={languageCode}&op=translate";
        //            driver.Navigate().GoToUrl(url);

        //            Thread.Sleep(sleepTime);
        //           // Thread.Sleep(1000);

        //            var sourceTextBox = driver.FindElement(By.XPath("//textarea[@aria-label='Source text']"));

        //            foreach (var item in englishTexts)
        //            {

        //                // Locate the input box and enter the text

        //                sourceTextBox.Clear();
        //                sourceTextBox.SendKeys(item.EnglishText);

        //                // Wait for the translation to complete
        //                Thread.Sleep(sleepTime);
        //               // Thread.Sleep(1000);

        //                //// Retrieve the translated text
        //                //var outputBox = driver.FindElement(By.XPath("//div[@class='J0lOec']"));
        //                //result = outputBox.Text;

        //                // Wait for translation with WebDriverWait instead of Thread.Sleep
        //                var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));

        //                Thread.Sleep(sleepTime);
        //                // Thread.Sleep(1000);

        //                // var translationContainer = wait.Until(d => d.FindElement(By.ClassName("ryNqvb")));
        //                var translationContainer = wait.Until(d => d.FindElement(By.ClassName("usGWQd")));
        //                var result = translationContainer.Text;

        //                var translation = new Translation
        //                {
        //                    MainTableID = item.ID,
        //                    LanguageCode = languageCode,
        //                    TranslatedText = result,
        //                };

        //                _dbContext.Translation.Add(translation);
        //                await _dbContext.SaveChangesAsync();
        //                ViewBag.progress = o++;
        //            }

        //            // Wait for the page to load

        //        }
        //        catch (Exception ex)
        //        {
        //            throw new Exception($"Error during translation: {ex.Message}");
        //        }
        //        finally
        //        {
        //            driver.Quit();
        //        }
        //    }


        //    //ViewBag.ExecutionTime = $"Execution Time: {stopwatch.Elapsed.Minutes} minute(s) {stopwatch.Elapsed.Seconds} second(s)";
        //    return RedirectToAction("Index", "Translations");

        //}







        //BackUp It work
        //[HttpPost]
        //public async Task<IActionResult> TranslateAll(string languageCode)
        //{

        //        var englishTexts = await _dbContext.MainTables

LanguageInstallMVC/Controllers/TranslationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LanguageInstall.Data.Data;
using LanguageInstall.Data.Model;

namespace LanguageInstallMVC.Controllers
{
    public class TranslationsController : Controller
    {
        private readonly AppDbContext _context;

        public TranslationsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Translations
        public async Task<IActionResult> Index(string languageCode = null, string searchText = null)
        {
            // Start building the query with the Include
            var translationsQuery = _context.Translation
                .Include(t => t.MainTable) // Ensure Include is here
                .Where(t => string.IsNullOrEmpty(languageCode) || t.LanguageCode == languageCode);

            // If searchText is provided, filter by EnglishText or TranslatedText
            if (!string.IsNullOrEmpty(searchText))
            {
                translationsQuery = translationsQuery.Where(t =>
                    t.MainTable.EnglishText.Contains(searchText) || t.TranslatedText.Contains(searchText));
            }

            // Await the translations query to get the filtered results
            var translations = await translationsQuery.ToListAsync();

            // Fetch distinct language codes
            var languageCodes = await _context.Translation
                .Select(t => t.LanguageCode)
                .Distinct()
                .ToListAsync();

            // Pass the language codes and search text to the view
            ViewData["LanguageCodes"] = languageCodes;
            ViewBag.lang = languageCodes;
            ViewBag.SearchText = searchText;

            return View(translations);
        }


        // GET: Translations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var translation = await _context.Translation
                .Include(t => t.MainTable)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (translation == null)
            {
                return NotFound();
            }

            return View(translation);
        }

        // GET: Translations/Create
        public IActionResult Create()
        {
            ViewData["MainTableID"] = new SelectList(_context.MainTables, "ID", "EnglishText");
            return View();
        }

        // POST: Translations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,MainTableID,LanguageCode,TranslatedText")] Translation translation)
        {
            try
            {
                _context.Add(translation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

                throw;
            }
            //if (ModelState.IsValid)
            //{
            //    _context.Add(translation);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["MainTableID"] = new SelectList(_context.MainTables, "ID", "EnglishText", translation.MainTableID);
            //return View(translation);
        }

        // GET: Translations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var translation = await _context.Translation.FindAsync(id);
            if (translation == null)
            {
                return NotFound();
            }
            ViewData["MainTableID"] = new SelectList(_context.MainTables, "ID", "EnglishText", translation.MainTableID);
            return View(translation);
        }

        // POST: Translations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,MainTableID,LanguageCode,TranslatedText")] Translation translation)
        {
            if (id != translation.ID)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
                try
                {
                    _context.Update(translation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TranslationExists(translation.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            //}
            //ViewData["MainTableID"] = new SelectList(_context.MainTables, "ID", "EnglishText", translation.MainTableID);
            //return View(translation);
        }

        // GET: Translations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var translation = await _context.Translation
                .Include(t => t.MainTable)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (translation == null)
            {
                return NotFound();
            }

            return View(translation);
        }

        // POST: Translations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var translation = await _context.Translation.FindAsync(id);
            if (translation != null)
            {
                _context.Translation.Remove(translation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TranslationExists(int id)
        {
            return _context.Translation.Any(e => e.ID == id);
        }
    }
}

LanguageInstallMVC/Views/Shared/TranslationHelper.cshtml
@using LanguageInstall.Service 
@inject LanguageInstall.Service.Service.ILocalizationService TranslationService 

@functions {
    public async Task<string> TranslateAsync(string key, string languageCode)
    {
        return await TranslationService.GetTranslationAsync(key, languageCode);
    }
}

LanguageInstallMVC/Views/Shared/_Layout.cshtml
@inject LanguageInstall.Service.Service.ILocalizationService TranslationService
@inject IHttpContextAccessor HttpContextAccessor

@{
    // Access HttpContext via HttpContextAccessor
    var languageCode = HttpContextAccessor.HttpContext?.Items["Language"] as string ?? "en";
}

@{
    // Await the asynchronous method to get the languages list
    var languages = await TranslationService.GetLang();
}

<!DOCTYPE html>
<html lang="@languageCode">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LanguageInstallMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LanguageInstallMVC.styles.css" asp-append-version="true" />

    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">

    <!-- DataTables JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Language Install MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Form1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="RazorHelper">Form2</a>
                        </li>
                        @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Translate" asp-action="Index">translateIndex</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Translate" asp-action="Translate">Translate-Test</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MainTables" asp-action="Index">Label-text</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Translations" asp-action="Index">MultiLang-text</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Translate" asp-action="TranslateAll">Install-Language</a>
                        </li>
                        <!-- Other menu items here -->
                    </ul>

                    <!-- Language Dropdown -->
                    <ul class="navbar-nav ms-auto"> <!-- 'ms-auto' aligns it to the right -->
                        <li class="nav-item">
                            <select id="languageCode" name="languageCode" class="form-control form-control-sm" onchange="window.location.href='/Home/ChangeLanguage?languageCode=' + this.value;">
                                <option value="">-- Select Language --</option>
                                @foreach (var language in languages)
                                {
                                    <option value="@language" >@language</option>
                                }
                            </select>
                        </li>
                        
                    </ul>
                </div>
            </div>
          

             <div id="google_translate_element"></div> 
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - LanguageInstallMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


  @*  <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en',
                includedLanguages: 'af,sq,am,ar,hy,az,eu,be,bn,bs,bg,ca,ceb,ny,zh-CN,zh-TW,co,hr,cs,da,nl,en,eo,et,tl,fi,fr,fy,gl,ka,de,el,gu,ht,ha,haw,iw,hi,hmn,hu,is,ig,id,ga,it,ja,jw,kn,kk,km,ko,ku,ky,lo,la,lv,lt,lb,mk,mg,ms,ml,mt,mi,mr,mn,my,ne,no,or,ps,fa,pl,pt,pa,ro,ru,sm,gd,sr,st,sn,sd,si,sk,sl,so,es,su,sw,sv,tg,ta,te,th,tr,uk,ur,ug,uz,vi,cy,xh,yi,yo,zu',
                layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL
            }, 'google_translate_element');
        }
    </script>
     <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script> *@


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>