LanguageInstallMVC/Controllers/TranslationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LanguageInstall.Data.Data;
using LanguageInstall.Data.Model;

namespace LanguageInstallMVC.Controllers
{
    public class TranslationsController : Controller
    {
        private readonly AppDbContext _context;

        public TranslationsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Translations
        public async Task<IActionResult> Index(string languageCode = null, string searchText = null)
        {
            // Start building the query with the Include
            var translationsQuery = _context.Translation
                .Include(t => t.MainTable) // Ensure Include is here
                .Where(t => string.IsNullOrEmpty(languageCode) || t.LanguageCode == languageCode);

            // If searchText is provided, filter by EnglishText or TranslatedText
            if (!string.IsNullOrEmpty(searchText))
            {
                translationsQuery = translationsQuery.Where(t =>
                    t.MainTable.EnglishText.Contains(searchText) || t.TranslatedText.Contains(searchText));
            }

            // Await the translations query to get the filtered results
            var translations = await translationsQuery.ToListAsync();

            // Fetch distinct language codes
            var languageCodes = await _context.Translation
                .Select(t => t.LanguageCode)
                .Distinct()
                .ToListAsync();

            // Pass the language codes and search text to the view
            ViewData["LanguageCodes"] = languageCodes;
            ViewBag.lang = languageCodes;
            ViewBag.SearchText = searchText;

            return View(translations);
        }


        // GET: Translations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var translation = await _context.Translation
                .Include(t => t.MainTable)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (translation == null)
            {
                return NotFound();
            }

            return View(translation);
        }

        // GET: Translations/Create
        public IActionResult Create()
        {
            ViewData["MainTableID"] = new SelectList(_context.MainTables, "ID", "EnglishText");
            return View();
        }

        // POST: Translations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,MainTableID,LanguageCode,TranslatedText")] Translation translation)
        {
            try
            {
                _context.Add(translation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

                throw;
            }
            //if (ModelState.IsValid)
            //{
            //    _context.Add(translation);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["MainTableID"] = new SelectList(_context.MainTables, "ID", "EnglishText", translation.MainTableID);
            //return View(translation);
        }

        // GET: Translations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var translation = await _context.Translation.FindAsync(id);
            if (translation == null)
            {
                return NotFound();
            }
            ViewData["MainTableID"] = new SelectList(_context.MainTables, "ID", "EnglishText", translation.MainTableID);
            return View(translation);
        }

        // POST: Translations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,MainTableID,LanguageCode,TranslatedText")] Translation translation)
        {
            if (id != translation.ID)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
                try
                {
                    _context.Update(translation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TranslationExists(translation.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            //}
            //ViewData["MainTableID"] = new SelectList(_context.MainTables, "ID", "EnglishText", translation.MainTableID);
            //return View(translation);
        }

        // GET: Translations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var translation = await _context.Translation
                .Include(t => t.MainTable)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (translation == null)
            {
                return NotFound();
            }

            return View(translation);
        }

        // POST: Translations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var translation = await _context.Translation.FindAsync(id);
            if (translation != null)
            {
                _context.Translation.Remove(translation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TranslationExists(int id)
        {
            return _context.Translation.Any(e => e.ID == id);
        }
    }
}

LanguageInstallMVC/Views/Translations/Create.cshtml
@model LanguageInstall.Data.Model.Translation

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Translation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MainTableID" class="control-label"></label>
                <select asp-for="MainTableID" class ="form-control" asp-items="ViewBag.MainTableID"></select>
            </div>
            <div class="form-group">
                <label asp-for="LanguageCode" class="control-label"></label>
                <input asp-for="LanguageCode" class="form-control" />
                <span asp-validation-for="LanguageCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TranslatedText" class="control-label"></label>
                <input asp-for="TranslatedText" class="form-control" />
                <span asp-validation-for="TranslatedText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LanguageInstallMVC/Views/Translations/Delete.cshtml
@model LanguageInstall.Data.Model.Translation

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Translation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LanguageCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LanguageCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TranslatedText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TranslatedText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MainTable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MainTable.EnglishText)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LanguageInstallMVC/Views/Translations/Details.cshtml
@model LanguageInstall.Data.Model.Translation

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Translation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LanguageCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LanguageCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TranslatedText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TranslatedText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MainTable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MainTable.EnglishText)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LanguageInstallMVC/Views/Translations/Edit.cshtml
@model LanguageInstall.Data.Model.Translation

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Translation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="MainTableID" class="control-label"></label>
                <select asp-for="MainTableID" class="form-control" asp-items="ViewBag.MainTableID"></select>
                <span asp-validation-for="MainTableID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LanguageCode" class="control-label"></label>
                <input asp-for="LanguageCode" class="form-control" />
                <span asp-validation-for="LanguageCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TranslatedText" class="control-label"></label>
                <input asp-for="TranslatedText" class="form-control" />
                <span asp-validation-for="TranslatedText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LanguageInstallMVC/Views/Translations/Index.cshtml
@model IEnumerable<LanguageInstall.Data.Model.Translation>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Translations</h1>

<!-- Language dropdown -->
<form method="get" action="@Url.Action("Index", "Translations")">

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="languageCode">Select Language</label>
                <select id="languageCode" name="languageCode" class="form-control">
                    <option value="">-- All Languages --</option>
                    @* @foreach (var languageCode in ViewData["LanguageCodes"] as List<string>) *@
                    @foreach (var languageCode in ViewBag.lang)
                    {
                        <option value="@languageCode">@languageCode</option>
                    }
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="searchText">Search</label>
                <input type="text" id="searchText" name="searchText" class="form-control" value="@ViewBag.SearchText" placeholder="Search in English or Translated Text" />
            </div>
        </div>
    </div>


    
    
    <button type="submit" class="btn btn-primary mt-2">Filter</button>
</form>

<!-- Translations Table -->
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.LanguageCode)</th>
            <th>@Html.DisplayNameFor(model => model.TranslatedText)</th>
            <th>@Html.DisplayNameFor(model => model.MainTable)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.LanguageCode)</td>
                <td>@Html.DisplayFor(modelItem => item.TranslatedText)</td>
                <td>@Html.DisplayFor(modelItem => item.MainTable.EnglishText)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>